/*
 * Dyspatch API
 * # Introduction  The Dyspatch API is based on the REST paradigm and features resource based URLs with standard HTTP response codes to indicate errors. We use standard HTTP authentication and request verbs and all responses are JSON formatted. See our [Implementation Guide](https://docs.dyspatch.io/development/implementing_dyspatch/) for more details on how to implement Dyspatch.  ## API Client Libraries  Dyspatch provides API Clients for the following languages and web frameworks:  - [Java](https://github.com/getdyspatch/dyspatch-java) - [Javascript](https://github.com/getdyspatch/dyspatch-javascript) - [Python](https://github.com/getdyspatch/dyspatch-python) - [C#](https://github.com/getdyspatch/dyspatch-dotnet) - [Go](https://github.com/getdyspatch/dyspatch-golang) - [Ruby](https://github.com/getdyspatch/dyspatch-ruby) 
 *
 * OpenAPI spec version: 2019.10
 * Contact: support@dyspatch.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.dyspatch.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.dyspatch.client.model.DraftMetaRead;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * DraftsRead
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-12-04T10:55:38.642-08:00")
public class DraftsRead {
  @SerializedName("cursor")
  private Object cursor = null;

  @SerializedName("data")
  private List<DraftMetaRead> data = null;

  public DraftsRead cursor(Object cursor) {
    this.cursor = cursor;
    return this;
  }

   /**
   * Information about paginated results
   * @return cursor
  **/
  @ApiModelProperty(value = "Information about paginated results")
  public Object getCursor() {
    return cursor;
  }

  public void setCursor(Object cursor) {
    this.cursor = cursor;
  }

  public DraftsRead data(List<DraftMetaRead> data) {
    this.data = data;
    return this;
  }

  public DraftsRead addDataItem(DraftMetaRead dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<DraftMetaRead>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * A list of draft metadata objects
   * @return data
  **/
  @ApiModelProperty(value = "A list of draft metadata objects")
  public List<DraftMetaRead> getData() {
    return data;
  }

  public void setData(List<DraftMetaRead> data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DraftsRead draftsRead = (DraftsRead) o;
    return Objects.equals(this.cursor, draftsRead.cursor) &&
        Objects.equals(this.data, draftsRead.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cursor, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DraftsRead {\n");
    
    sb.append("    cursor: ").append(toIndentedString(cursor)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

