/*
 * Dyspatch API
 * # Introduction  The Dyspatch API is based on the REST paradigm and features resource based URLs with standard HTTP response codes to indicate errors. We use standard HTTP authentication and request verbs and all responses are JSON formatted. See our [Implementation Guide](https://docs.dyspatch.io/development/implementing_dyspatch/) for more details on how to implement Dyspatch.  ## API Client Libraries  Dyspatch provides API Clients for the following languages and web frameworks:  - [Java](https://github.com/getdyspatch/dyspatch-java) - [Javascript](https://github.com/getdyspatch/dyspatch-javascript) - [Python](https://github.com/getdyspatch/dyspatch-python) - [C#](https://github.com/getdyspatch/dyspatch-dotnet) - [Go](https://github.com/getdyspatch/dyspatch-golang) - [Ruby](https://github.com/getdyspatch/dyspatch-ruby) 
 *
 * OpenAPI spec version: 2019.10
 * Contact: support@dyspatch.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.dyspatch.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * LocalizationMetaRead
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-12-04T10:26:06.860-08:00")
public class LocalizationMetaRead {
  @SerializedName("id")
  private String id = null;

  @SerializedName("language")
  private String language = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("draft")
  private String draft = null;

  public LocalizationMetaRead id(String id) {
    this.id = id;
    return this;
  }

   /**
   * An opaque, unique identifier for a localization
   * @return id
  **/
  @ApiModelProperty(example = "loc_g3L7Cw6Hp5wUaf395LehwK", value = "An opaque, unique identifier for a localization")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public LocalizationMetaRead language(String language) {
    this.language = language;
    return this;
  }

   /**
   * A language identifier comprised of a language and a country identifier.  See [supported languages](https://docs.dyspatch.io/localization/supported_languages/). 
   * @return language
  **/
  @ApiModelProperty(example = "en-US", value = "A language identifier comprised of a language and a country identifier.  See [supported languages](https://docs.dyspatch.io/localization/supported_languages/). ")
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public LocalizationMetaRead name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The user-specified name of a localization
   * @return name
  **/
  @ApiModelProperty(example = "English (US)", value = "The user-specified name of a localization")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public LocalizationMetaRead url(String url) {
    this.url = url;
    return this;
  }

   /**
   * The API url for a specific localization
   * @return url
  **/
  @ApiModelProperty(example = "/localizations/loc_g3L7Cw6Hp5wUaf395LehwK", value = "The API url for a specific localization")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public LocalizationMetaRead draft(String draft) {
    this.draft = draft;
    return this;
  }

   /**
   * An opaque, unique identifier for a draft
   * @return draft
  **/
  @ApiModelProperty(example = "tdft_g3L7Cw6Hp5wU", value = "An opaque, unique identifier for a draft")
  public String getDraft() {
    return draft;
  }

  public void setDraft(String draft) {
    this.draft = draft;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LocalizationMetaRead localizationMetaRead = (LocalizationMetaRead) o;
    return Objects.equals(this.id, localizationMetaRead.id) &&
        Objects.equals(this.language, localizationMetaRead.language) &&
        Objects.equals(this.name, localizationMetaRead.name) &&
        Objects.equals(this.url, localizationMetaRead.url) &&
        Objects.equals(this.draft, localizationMetaRead.draft);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, language, name, url, draft);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LocalizationMetaRead {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    draft: ").append(toIndentedString(draft)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

