/*
 * Dyspatch API
 * # Introduction  The Dyspatch API is based on the REST paradigm, and features resource based URLs with standard HTTP response codes to indicate errors. We use standard HTTP authentication and request verbs, and all responses are JSON formatted. See our [Implementation Guide](https://docs.dyspatch.io/development/implementing_dyspatch/) for more details on how to implement Dyspatch.  ## API Client Libraries Dyspatch provides API Clients for popular languages and web frameworks.  - [Java](https://github.com/getdyspatch/dyspatch-java) - [Javascript](https://github.com/getdyspatch/dyspatch-javascript) - [Python](https://github.com/getdyspatch/dyspatch-python) - [C#](https://github.com/getdyspatch/dyspatch-dotnet) - [Go](https://github.com/getdyspatch/dyspatch-golang) - [Ruby](https://github.com/getdyspatch/dyspatch-ruby) 
 *
 * The version of the OpenAPI document: 2020.11
 * Contact: support@dyspatch.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.dyspatch.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.dyspatch.client.model.CompiledRead;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * localization metadata and latest revision for associated template
 */
@ApiModel(description = "localization metadata and latest revision for associated template")

public class LocalizationRead {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_LANGUAGES = "languages";
  @SerializedName(SERIALIZED_NAME_LANGUAGES)
  private List<String> languages = null;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;

  public static final String SERIALIZED_NAME_TEMPLATE = "template";
  @SerializedName(SERIALIZED_NAME_TEMPLATE)
  private String template;

  public static final String SERIALIZED_NAME_COMPILED = "compiled";
  @SerializedName(SERIALIZED_NAME_COMPILED)
  private CompiledRead compiled;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private OffsetDateTime updatedAt;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_LOCALE_GROUP = "localeGroup";
  @SerializedName(SERIALIZED_NAME_LOCALE_GROUP)
  private String localeGroup;


  public LocalizationRead id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * An opaque, unique identifier for a localization
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "loc_g3L7Cw6Hp5wUaf395LehwK", value = "An opaque, unique identifier for a localization")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public LocalizationRead languages(List<String> languages) {
    
    this.languages = languages;
    return this;
  }

  public LocalizationRead addLanguagesItem(String languagesItem) {
    if (this.languages == null) {
      this.languages = new ArrayList<>();
    }
    this.languages.add(languagesItem);
    return this;
  }

   /**
   * a list of locale codes that are available in the localization. See [supported languages](https://docs.dyspatch.io/localization/supported_languages/) for an exhaustive list of locale codes. 
   * @return languages
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "a list of locale codes that are available in the localization. See [supported languages](https://docs.dyspatch.io/localization/supported_languages/) for an exhaustive list of locale codes. ")

  public List<String> getLanguages() {
    return languages;
  }


  public void setLanguages(List<String> languages) {
    this.languages = languages;
  }


  public LocalizationRead url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * The API url for a specific localization
   * @return url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "/localizations/loc_g3L7Cw6Hp5wUaf395LehwK", value = "The API url for a specific localization")

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  public LocalizationRead template(String template) {
    
    this.template = template;
    return this;
  }

   /**
   * An opaque, unique identifier for a template
   * @return template
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "tem_g3L7Cw6Hp5wU", value = "An opaque, unique identifier for a template")

  public String getTemplate() {
    return template;
  }


  public void setTemplate(String template) {
    this.template = template;
  }


  public LocalizationRead compiled(CompiledRead compiled) {
    
    this.compiled = compiled;
    return this;
  }

   /**
   * Get compiled
   * @return compiled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public CompiledRead getCompiled() {
    return compiled;
  }


  public void setCompiled(CompiledRead compiled) {
    this.compiled = compiled;
  }


  public LocalizationRead createdAt(OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * The time of initial creation
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The time of initial creation")

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public LocalizationRead updatedAt(OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * The time of last update
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The time of last update")

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public LocalizationRead name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The user-specified name of a localization
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "English (US)", value = "The user-specified name of a localization")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public LocalizationRead localeGroup(String localeGroup) {
    
    this.localeGroup = localeGroup;
    return this;
  }

   /**
   * the locale group this localization belongs to, if this field is empty the localization does not belong to any locale group
   * @return localeGroup
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "lgr_alka38ajla301", value = "the locale group this localization belongs to, if this field is empty the localization does not belong to any locale group")

  public String getLocaleGroup() {
    return localeGroup;
  }


  public void setLocaleGroup(String localeGroup) {
    this.localeGroup = localeGroup;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LocalizationRead localizationRead = (LocalizationRead) o;
    return Objects.equals(this.id, localizationRead.id) &&
        Objects.equals(this.languages, localizationRead.languages) &&
        Objects.equals(this.url, localizationRead.url) &&
        Objects.equals(this.template, localizationRead.template) &&
        Objects.equals(this.compiled, localizationRead.compiled) &&
        Objects.equals(this.createdAt, localizationRead.createdAt) &&
        Objects.equals(this.updatedAt, localizationRead.updatedAt) &&
        Objects.equals(this.name, localizationRead.name) &&
        Objects.equals(this.localeGroup, localizationRead.localeGroup);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, languages, url, template, compiled, createdAt, updatedAt, name, localeGroup);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LocalizationRead {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    languages: ").append(toIndentedString(languages)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("    compiled: ").append(toIndentedString(compiled)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    localeGroup: ").append(toIndentedString(localeGroup)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

