/*
 * Dyspatch API
 * # Introduction  The Dyspatch API is based on the REST paradigm, and features resource based URLs with standard HTTP response codes to indicate errors. We use standard HTTP authentication and request verbs, and all responses are JSON formatted. See our [Implementation Guide](https://docs.dyspatch.io/development/implementing_dyspatch/) for more details on how to implement Dyspatch.  ## API Client Libraries Dyspatch provides API Clients for popular languages and web frameworks.  - [Java](https://github.com/getdyspatch/dyspatch-java) - [Javascript](https://github.com/getdyspatch/dyspatch-javascript) - [Python](https://github.com/getdyspatch/dyspatch-python) - [C#](https://github.com/getdyspatch/dyspatch-dotnet) - [Go](https://github.com/getdyspatch/dyspatch-golang) - [Ruby](https://github.com/getdyspatch/dyspatch-ruby) 
 *
 * The version of the OpenAPI document: 2020.04
 * Contact: support@dyspatch.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.dyspatch.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * localization metadata
 */
@ApiModel(description = "localization metadata")

public class LocalizationMetaRead {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;

  public static final String SERIALIZED_NAME_LOCALE_GROUP = "localeGroup";
  @SerializedName(SERIALIZED_NAME_LOCALE_GROUP)
  private String localeGroup;

  public static final String SERIALIZED_NAME_LANGUAGES = "languages";
  @SerializedName(SERIALIZED_NAME_LANGUAGES)
  private List<String> languages = null;


  public LocalizationMetaRead id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * An opaque, unique identifier for a localization
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "loc_g3L7Cw6Hp5wUaf395LehwK", value = "An opaque, unique identifier for a localization")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public LocalizationMetaRead name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The user-specified name of a localization
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "English (US)", value = "The user-specified name of a localization")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public LocalizationMetaRead url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * The API url for a specific localization
   * @return url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "/localizations/loc_g3L7Cw6Hp5wUaf395LehwK", value = "The API url for a specific localization")

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  public LocalizationMetaRead localeGroup(String localeGroup) {
    
    this.localeGroup = localeGroup;
    return this;
  }

   /**
   * the locale group this localization belongs to, if this field is empty the localization does not belong to any locale group
   * @return localeGroup
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "lgr_alka38ajla301", value = "the locale group this localization belongs to, if this field is empty the localization does not belong to any locale group")

  public String getLocaleGroup() {
    return localeGroup;
  }


  public void setLocaleGroup(String localeGroup) {
    this.localeGroup = localeGroup;
  }


  public LocalizationMetaRead languages(List<String> languages) {
    
    this.languages = languages;
    return this;
  }

  public LocalizationMetaRead addLanguagesItem(String languagesItem) {
    if (this.languages == null) {
      this.languages = new ArrayList<String>();
    }
    this.languages.add(languagesItem);
    return this;
  }

   /**
   * a list of locale codes that are available in the localization. See [supported languages](https://docs.dyspatch.io/localization/supported_languages/) for an exhaustive list of locale codes. 
   * @return languages
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "a list of locale codes that are available in the localization. See [supported languages](https://docs.dyspatch.io/localization/supported_languages/) for an exhaustive list of locale codes. ")

  public List<String> getLanguages() {
    return languages;
  }


  public void setLanguages(List<String> languages) {
    this.languages = languages;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LocalizationMetaRead localizationMetaRead = (LocalizationMetaRead) o;
    return Objects.equals(this.id, localizationMetaRead.id) &&
        Objects.equals(this.name, localizationMetaRead.name) &&
        Objects.equals(this.url, localizationMetaRead.url) &&
        Objects.equals(this.localeGroup, localizationMetaRead.localeGroup) &&
        Objects.equals(this.languages, localizationMetaRead.languages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, url, localeGroup, languages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LocalizationMetaRead {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    localeGroup: ").append(toIndentedString(localeGroup)).append("\n");
    sb.append("    languages: ").append(toIndentedString(languages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

