name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: techdroplabs/api-setup-action
          token: ${{ secrets.MACHINES_SWU_TOKEN }}
          ref: master
      - name: Run api setup action
        uses: ./
        with:
          email: ${{ secrets.QA_USERNAME }}
          password: ${{ secrets.QA_PASSWORD }}
          cognito_client_id: ${{ secrets.COGNITO_CLIENT_ID }}
          cognito_client_secret: ${{ secrets.COGNITO_CLIENT_SECRET }}
          cognito_pool_id: ${{ secrets.COGNITO_POOL_ID }}
          web_sso_host: ${{ secrets.WEB_SSO_HOST }}
          web_sso_redirect_host: ${{ secrets.WEB_SSO_REDIRECT_HOST }}
          graphql_host: ${{ secrets.GRAPHQL_HOST }}

      - uses: actions/checkout@v1

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 13

      - name: Build with Gradle
        run: ./gradlew build
        env:
          DYSPATCH_API_KEY: ${{ secrets.DYSPATCH_API_KEY }}
